"""
DrawQuantPDF - Configuration
Color ranges (HSV) and application settings.
"""

import os

APP_NAME = "DrawQuantPDF"
APP_VERSION = "1.0.0"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.join(BASE_DIR, "assets")

SCALE = 100  # 1:100

# HSV color ranges for detection
# Format: (H_min, S_min, V_min), (H_max, S_max, V_max)
# Facade: lower saturation (S>=45) — catches washed-out contour lines on point clouds
# Windows/Doors: strict saturation (S>=80) — needs clear fill color to avoid FP
# Note: on point cloud images with thin-line markup (S=50-60), windows/doors
# may not be auto-detected — user adds them manually via canvas.
COLOR_RANGES = {
    "facade": {
        "cyan": {"lower": (80, 45, 60), "upper": (105, 255, 255)},
        "blue": {"lower": (100, 45, 60), "upper": (130, 255, 255)},
    },
    "window": {
        "yellow": {"lower": (18, 80, 80), "upper": (35, 255, 255)},
        "green": {"lower": (35, 60, 60), "upper": (85, 255, 255)},
    },
    "door": {
        "orange": {"lower": (5, 100, 100), "upper": (20, 255, 255)},
        "red_low": {"lower": (0, 100, 100), "upper": (8, 255, 255)},
        "red_high": {"lower": (165, 100, 100), "upper": (180, 255, 255)},
        "magenta": {"lower": (140, 80, 80), "upper": (170, 255, 255)},
    },
}

# Minimum contour area (in pixels) to be considered a valid region
MIN_FACADE_AREA_PX = 5000
MIN_WINDOW_AREA_PX = 800
MIN_DOOR_AREA_PX = 800

# Photo detection: facade region
PHOTO_FACADE_ROI_Y_START = 0.15      # ROI top margin (fraction of image height)
PHOTO_FACADE_ROI_Y_END = 0.95        # ROI bottom margin
PHOTO_FACADE_ROOF_CUT_Y_START = 0.45 # Start searching for roof edge (fraction of ROI)
PHOTO_FACADE_ROOF_CUT_Y_END = 0.90   # End search for roof edge
PHOTO_FACADE_ROOF_CUT_MIN = 0.50    # Min valid cut ratio (reject if cut too high)
PHOTO_FACADE_ROOF_CUT_MAX = 0.88    # Max valid cut ratio (cut more aggressive)
PHOTO_FACADE_TOP_CUT_Y_START = 0.05  # Upper zone for roof/sky separation
PHOTO_FACADE_TOP_CUT_Y_END = 0.45
PHOTO_FACADE_TOP_CUT_MIN = 0.08
PHOTO_FACADE_TOP_CUT_MAX = 0.60
PHOTO_FACADE_TOP_CUT_PEAK_RATIO = 1.25
PHOTO_FACADE_MAX_HEIGHT_RATIO = 0.78  # Max facade height as fraction of image
PHOTO_FACADE_MIN_AREA_RATIO = 0.08   # Min facade area vs image area
PHOTO_FACADE_BG_BORDER_PERCENTILE = 65.0  # Border percentile used as background level
PHOTO_FACADE_BG_THRESHOLD_DELTA = 10.0    # Foreground threshold = bg - delta
PHOTO_FACADE_WALL_ROW_OCC_MIN = 0.78      # Start wall where occupancy reaches 78% of max
PHOTO_FACADE_WALL_ROW_OCC_MEAN = 0.74
PHOTO_FACADE_WALL_ROW_SCAN_MAX = 0.72
PHOTO_FACADE_WALL_COL_OCC_MIN = 0.08
PHOTO_FACADE_WALL_MIN_HEIGHT_RATIO = 0.20
PHOTO_FACADE_BOTTOM_CUT_Y_START = 0.55
PHOTO_FACADE_BOTTOM_CUT_Y_END = 0.97
PHOTO_FACADE_BOTTOM_CUT_MIN_BAND = 0.04
PHOTO_FACADE_BOTTOM_CUT_MAX_BAND = 0.30
PHOTO_FACADE_BOTTOM_CUT_PEAK_RATIO = 1.25
PHOTO_FACADE_SIDE_OCC_PERCENT_RATIO = 0.58
PHOTO_FACADE_SIDE_MIN_RUN_RATIO = 0.18
PHOTO_FACADE_SIDE_MARGIN_RATIO = 0.010
PHOTO_FACADE_SIDE_MIN_KEEP_RATIO = 0.72

# Socle detection and exclusion (auto-photo facades)
PHOTO_SOCLE_Y_START = 0.58
PHOTO_SOCLE_Y_END = 0.96
PHOTO_SOCLE_PEAK_RATIO = 1.22
PHOTO_SOCLE_FIRST_EDGE_RATIO = 0.72
PHOTO_SOCLE_MIN_BAND_RATIO = 0.04
PHOTO_SOCLE_MAX_BAND_RATIO = 0.30
PHOTO_SOCLE_MIN_ROW_OCC_RATIO = 0.28
PHOTO_SOCLE_MAX_AREA_SHARE = 0.50
PHOTO_SOCLE_FLAT_BOTTOM_MAX_IQR = 14.0
PHOTO_SOCLE_GUIDE_MIN_TOP_RATIO = 0.68
PHOTO_SOCLE_GUIDE_MIN_WIDTH_RATIO = 0.12
PHOTO_SOCLE_GUIDE_MIN_COVERAGE = 0.25
PHOTO_SOCLE_GUIDE_MAX_HEIGHT_RATIO = 0.22
PHOTO_SOCLE_GUIDE_MAX_SLOPE = 0.12
PHOTO_SOCLE_EDGE_BRIDGE_MAX_RATIO = 0.06

# Photo detection: window filters (reduce roof false positives)
PHOTO_WINDOW_MIN_WIDTH_RATIO = 0.020
PHOTO_WINDOW_STRICT_MIN_WIDTH_RATIO = 0.035
PHOTO_WINDOW_NARROW_MIN_HEIGHT_RATIO = 0.16
PHOTO_WINDOW_MIN_Y_RATIO = 0.12      # Reject windows in top 12% of facade (roof zone)
PHOTO_WINDOW_MAX_Y_RATIO = 0.92      # Reject windows in bottom 8% (socle zone)
PHOTO_WINDOW_MIN_LAPLACIAN_VAR = 22.0  # Reject flat textures (likely roof/sky)
PHOTO_WINDOW_MAX_BRIGHT_MEAN = 185.0   # Reject very bright candidate interiors
PHOTO_WINDOW_TEXTURE_STD_MIN = 24.0
PHOTO_WINDOW_LAPLACIAN_STRICT_MIN = 12000.0
PHOTO_WINDOW_APPEARANCE_GRADIENT_PERCENTILE = 91.0
PHOTO_WINDOW_APPEARANCE_BRIGHT_PERCENTILES = (78.0, 82.0)
PHOTO_WINDOW_LOCAL_CONTRAST_PERCENTILES = (82.0, 86.0)
PHOTO_WINDOW_LOCAL_CONTRAST_SIGMA_X_RATIO = 0.022
PHOTO_WINDOW_LOCAL_CONTRAST_SIGMA_Y_RATIO = 0.030
PHOTO_WINDOW_LOCAL_CONTRAST_STD_MIN = 14.0

PHOTO_FACADE_ATTACHMENT_MIN_WIDTH_RATIO = 0.10
PHOTO_FACADE_ATTACHMENT_MAX_WIDTH_RATIO = 0.78
PHOTO_FACADE_ATTACHMENT_MIN_HEIGHT_RATIO = 0.16
PHOTO_FACADE_ATTACHMENT_MIN_OVERLAP_RATIO = 0.45
PHOTO_FACADE_ATTACHMENT_TOUCH_RATIO = 0.14
PHOTO_FACADE_CAP_LINE_BIAS_RATIO = 0.05
PHOTO_FACADE_CAP_LINE_BIAS_MIN_PX = 10
PHOTO_FACADE_BODY_EDGE_TRIM_MAX_RATIO = 0.08
PHOTO_FACADE_BODY_ROW_OCC_RATIO = 0.58
PHOTO_FACADE_BODY_ROW_MEAN_RATIO = 0.62
PHOTO_FACADE_BODY_TOP_RELAX_PX = 4

PHOTO_SCENE_GABLE_MAX_ASPECT = 2.15
PHOTO_SCENE_GABLE_TOP_SPAN_RATIO = 0.28
PHOTO_SCENE_GABLE_TOP_IQR_RATIO = 0.12
PHOTO_SCENE_GABLE_PEAK_DELTA_RATIO = 0.10
PHOTO_SCENE_FLAT_MIN_ASPECT = 2.00
PHOTO_SCENE_FLAT_TOP_IQR_RATIO = 0.10
PHOTO_SCENE_COMPOSITE_MIN_OPENINGS = 4
PHOTO_SCENE_COMPOSITE_OPENING_TOP_SPREAD_RATIO = 0.12
PHOTO_SCENE_COMPOSITE_OPENING_CENTER_SPREAD_RATIO = 0.16
PHOTO_SCENE_BORDERLINE_TOP_SPAN_RATIO = 0.08
PHOTO_SCENE_BORDERLINE_MAX_OPENINGS = 4
PHOTO_SCENE_SPARSE_MAX_OPENINGS = 1

# Photo detection: door heuristics
PHOTO_DOOR_MIN_Y_RATIO = 0.42
PHOTO_DOOR_MAX_Y_RATIO = 0.94
PHOTO_DOOR_MIN_BOTTOM_RATIO = 0.72
PHOTO_DOOR_MIN_WIDTH_RATIO = 0.04
PHOTO_DOOR_MAX_WIDTH_RATIO = 0.28
PHOTO_DOOR_MIN_HEIGHT_RATIO = 0.20
PHOTO_DOOR_MAX_HEIGHT_RATIO = 0.82
PHOTO_DOOR_MIN_ASPECT = 0.28
PHOTO_DOOR_MAX_ASPECT = 1.25
PHOTO_DOOR_MIN_STD = 18.0
PHOTO_DOOR_MIN_LAPLACIAN = 2500.0
PHOTO_DOOR_LOCAL_CENTER_BLEND = 0.65
PHOTO_DOOR_LOCAL_MAX_SHIFT_RATIO = 0.45
PHOTO_DOOR_SIDELIGHT_SUPPRESS_CONTAIN_RATIO = 0.48
PHOTO_DOOR_BRIGHT_PERCENTILES = (72.0, 78.0)

# Automatic linear scale fallback for white-background extracted facades.
AUTO_ASSUME_SCALE_ENABLED = True
AUTO_ASSUME_SCALE_WHITE_BORDER_MIN = 240.0
AUTO_ASSUME_SCALE_GEOMETRY_FALLBACK = True
AUTO_ASSUME_SCALE_DPI_DEVIATION_MAX_RATIO = 0.15

# OCR settings
OCR_LANGUAGES = ["ro", "en"]
OCR_GPU = False

# Excel export
EXCEL_TEMPLATE_HEADERS = [
    "Nr. Crt.",
    "Fatada",
    "Element",
    "Tip",
    "Latime (m)",
    "Inaltime (m)",
    "Suprafata (m²)",
]

# PDF conversion DPI
PDF_DPI = 254  # ~1:100 on A3 paper

